@baseUrl = http://localhost:3000

### Create memory
POST {{baseUrl}}/memories
Content-Type: application/json

{
  "title": "Minha memoria",
  "description": "Teste de criacao",
  "image": "https://example.com/image.jpg"
}

### Create memory (multipart)
POST {{baseUrl}}/memories
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Minha memoria
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Teste de criacao
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="foto.jpg"
Content-Type: image/jpeg

< ./images/foto.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get memories
GET {{baseUrl}}/memories

### Get memory by id
GET {{baseUrl}}/memories/SEU_ID_AQUI

### Delete memory by id
DELETE {{baseUrl}}/memories/SEU_ID_AQUI

### Update memory (multipart)
PATCH {{baseUrl}}/memories/SEU_ID_AQUI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Outro titulo
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Alguma descricao 2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="foto.jpg"
Content-Type: image/jpeg

< ./images/foto.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
